services:
    postgres:
        image: postgres:18.4-bookworm
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: always

    tg_bot:
        container_name: tg_bot
        build:
            context: ./
            dockerfile: services/tg_bot/Dockerfile
            args:
                NEXUS_PYPI_INDEX_URL: ${NEXUS_PYPI_INDEX_URL}
        environment:
            - Postgresql__host=${Postgresql__host}
            - Postgresql__port=${Postgresql__port}
            - Postgresql__user=${Postgresql__user}
            - Postgresql__password=${Postgresql__password}
            - Postgresql__db=${Postgresql__db}
            - ADMIN_ID=${ADMIN_ID}
            - TG_BOT_KEY=${TG_BOT_KEY}
        depends_on:
            postgres:
                condition: service_healthy
        restart: always

volumes:
    postgres_data:
