services:
    postgres_test:
        image: postgres:18.4-bookworm
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "127.0.0.1:5432:5432"
        expose:
            - 5432
        volumes:
            - postgres_test_data:/var/lib/postgresql
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    tg-bot-test:
        build:
            context: ./
            dockerfile: services/tg_bot/tests/Dockerfile
        # command: >
        #     sh -c "export PYTHONPATH=/app &&
        #             pytest services/tg_bot/tests -q"
        environment:
            - Postgresql__host=${Postgresql__host}
            - Postgresql__port=${Postgresql__port}
            - Postgresql__user=${Postgresql__user}
            - Postgresql__password=${Postgresql__password}
            - Postgresql__db=${Postgresql__db}
            - ADMIN_ID=${ADMIN_ID}
            - TG_BOT_KEY=${TG_BOT_KEY}
        depends_on:
            postgres_test:
                condition: service_healthy
        restart: no

volumes:
    postgres_test_data:
