"""initial revision

Revision ID: 1c24fa128f0b
Revises:
Create Date: 2026-05-22 22:38:58.892040

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1c24fa128f0b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
