"""create eng.idiom_phrase

Revision ID: 5e619a0479ae
Revises: ee3d3cbba0ee
Create Date: 2026-10-03 17:52:33.337211

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5e619a0479ae"
down_revision: str | Sequence[str] | None = "ee3d3cbba0ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idiom_phrase",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="identifier"),
        sa.Column("idiom", sa.String(), nullable=False, comment="idiom phrase"),
        sa.Column("translation", sa.String(), nullable=False, comment="translation to russian"),
        sa.Column("meaning", sa.String(), nullable=False, comment="meaning of idiom phrase"),
        sa.Column(
            "context", sa.String(), nullable=False, comment="context of usage for idiom phrase"
        ),
        sa.Column("source", sa.String(), nullable=False, comment="source of knowledge"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idiom"),
        schema="eng",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
