"""create eng.irregular_verb table

Revision ID: d281bad4966c
Revises: caad856cc7f7
Create Date: 2026-05-23 19:09:15.636904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d281bad4966c"
down_revision: Union[str, Sequence[str], None] = "caad856cc7f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "irregular_verb",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("base_form", sa.String(), nullable=False),
        sa.Column("past_simple", sa.String(), nullable=False),
        sa.Column("past_participle", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("base_form"),
        schema="eng",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
