name: Deploy to Virtual Machine

on:
    push:
        branches:
            - main
env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SERVER_PORT }}
                  script: |
                      cd /root/dev/irregular_bot
                      git pull origin main
                      docker-compose down
                      docker-compose up -d --build
